### ISSUE TITLE
Conexão Bluetooth

### ISSUE THREAD

**Issue by mguilhermetavares** [stone-payments/sdk-android#14]
Versão 2.3.1 SDK
Ao chamar GlobalInformations.getPinpadFromListAt(0);  é lancada uma Exception

 java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at stone.utils.GlobalInformations.getPinpadFromListAt(GlobalInformations.java:70)

porém o celular está conectado com o pinpad.

**Comment by rubenspessoa** [comment]
O mesmo está acontecendo comigo. @mguilhermetavares caso consiga achar um workaround, compartilha aqui, por favor. Farei o mesmo caso consiga consertar!

**Comment by filpgame** [comment]
Boa tarde pessoal
Isso acontece sempre? mesmo logo depois de conectar com o pinpad?

**Comment by rubenspessoa** [comment]
O que acontece aqui é que eu consigo conectar com o pinpad em uma tela, mas quando vou finalizar a transação ele lança esse erro. Fiquei tentando repetir a operação e em alguns dos meus testes também foi lançado um erro: "Dispositivo (pinpad) incompatível" ou algo similar. Vou tentar reproduzir o erro novamente pra trazer mais informações.

**Comment by rubenspessoa** [comment]
@mguilhermetavares Dá uma conferida se você não está tentando conectar ao pinpad mais de uma vez, depois que eu mexi nisso o erro não apareceu mais, mas não sei se isso está relacionado.

Agora apareceu o seguinte erro: 

08-01 17:22:44.548 9831-9831/? E/SingleFlowSampleHandler: Should not be flowing when InputConnectionDelegator.composing() is false!

**Comment by tio-ze** [comment]
Olá amigos. Mesmo erro comigo, não sei se aqui é o lugar certo. Versão 2.3.1. Segue stacktrace:

I/PinpadSize: 1
V/STONE_BLUETOOTH: > Start method doInBackground()
V/STONE_BLUETOOTH: > Step 1. Creating connection 
W/GAv4: onServiceConnected received after the timeout limit
V/STONE_BLUETOOTH: > Step 2. [REQUEST] Creating RFCOMM socket
W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@ff73a5b time:17689203
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@ff73a5b time:17689203
W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
W/System.err:     at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:764)
W/System.err:     at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:723)
W/System.err:     at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:388)
W/System.err:     at stone.providers.BluetoothConnectionProvider.doInBackground(BluetoothConnectionProvider.java:109)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
E/STONE_BLUETOOTH: > EXCEPTION IOException
V/STONE_BLUETOOTH: > Time to create connection: 0m 0s

**Comment by jgabrielfreitas** [comment]
@tio-ze @mguilhermetavares @rubenspessoa qual a versão do Android e o modelo do pinpad que estão usando?

**Comment by tio-ze** [comment]
Olá @jgabrielfreitas . O @rubenspessoa deu uma dica interessante. O erro comigo só aparece quando eu tento conectar com ele já conectado, o que não me parece adequado já que eu não tenho como saber se já está conectado. Enfim.
Fiz um workaround e consegui andar no projeto. Mas tem coisa estranha ai rs

**Comment by jgabrielfreitas** [comment]
Estou com a suspeita que seja o mapeamento do device dentro da SDK.
Ele pode estar conectado via bluetooth, mas a SDK não encontrando, uma vez que ele pode ter sido removido da lista interna. 
Vou dar uma olhada aqui, se vocês arrumarem uma forma de reproduzir este erro, seria muito bom, até pra trabalhar direto em cima desse caso. Mas de qualquer forma, estou vendo o caso

**Comment by rubenspessoa** [comment]
@jgabrielfreitas Estou usando a versão 7.0 do Android e o modelo D150 do Pinpad.

**Comment by mguilhermetavares** [comment]
@jgabrielfreitas estou usando a versão MOBI PIN 10.

**Comment by mguilhermetavares** [comment]
Estou usando a versão 2.3.0 e este problema não aparece. Acho que está na 2.3.1 mesmo

**Comment by jgabrielfreitas** [comment]
Eu estou testando com um Samsung android 4.1 e um nexus 5 android 7.1 (com uma custom ROM) e 3 pinpads, D200, Mobi Pin 10 e D150

**Comment by lucasmacielc** [comment]
Esse erro ainda acontece, atualmente estou na versão 2.4.3. Vocês tem N maneiras de resolver, hoje para contornar o problema estou verificando a lista antes de chamar este método.

**Comment by mguilhermetavares** [comment]
@lucasmacielc essa é uma ótima solução para contornar o problema.  (y)

**Comment by lucasmacielc** [comment]
@mguilhermetavares  é uma ótima solução, porém não é a ideal. Pois sempre que preciso utilizar a conexão entre os dois preciso fazer essa verificação.
