### ISSUE TITLE
Timeout durante o passo TRANSACTION_WAITING_REMOVE

### ISSUE THREAD

**Issue by italololiveira** [stone-payments/sdk-android#16]
Olá! Segue abaixo os dados do dispositivo e da versão da api:

Dispositivo: Moto X Play XT1563, Android API 23
Versões API Stone testadas: 2.3.2 , 2.4.0, 2.4.2
Ambientes: Produção e Sandbox
Pinpad testado: Mobipin 10

Stacktrace do erro: 

```
08-30 10:18:36.865 12744-13662/br.com.teste W/System.err: java.io.IOException: Timeout
08-30 10:18:36.880 12744-13662/br.com.teste W/System.err:     at stone.providers.CommandReader.read(CommandReader.java:164)
08-30 10:18:36.880 12744-13662/br.com.teste W/System.err:     at stone.providers.CommandReader.getResponse(CommandReader.java:74)
08-30 10:18:36.880 12744-13662/br.com.teste W/System.err:     at stone.providers.TransactionProvider.doInBackground(TransactionProvider.java:302)
08-30 10:18:36.880 12744-13662/br.com.teste W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-30 10:18:36.880 12744-13662/br.com.teste W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-30 10:18:36.880 12744-13662/br.com.teste W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-30 10:18:36.881 12744-13662/br.com.teste W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-30 10:18:36.881 12744-13662/br.com.teste W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-30 10:18:36.881 12744-13662/br.com.teste W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-30 10:18:36.881 12744-13662/br.com.teste W/System.err: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=3
08-30 10:18:36.886 12744-13662/br.com.teste W/System.err:     at java.lang.String.startEndAndLength(String.java:298)
08-30 10:18:36.886 12744-13662/br.com.teste W/System.err:     at java.lang.String.substring(String.java:1087)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at stone.providers.CommandReader.getResponse(CommandReader.java:75)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at stone.providers.TransactionProvider.doInBackground(TransactionProvider.java:302)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-30 10:18:36.887 12744-13662/br.com.teste W/System.err:     at java.lang.Thread.run(Thread.java:818)

```

Passos para reproduzir:

1 - Realizar transação como normal.
2 - No momento em que aparecer a mensagem no PinPad "Retire o Cartão" esperar até 20 segundos.
3 - Nesse momento o erro aparece no log e o callback de erro é chamado.

Obs: Ao chamar o callback de erro a lista de erros está vazia.
Obs: Problema ocorre independente da transação ser aprovada ou não.

**Comment by filpgame** [comment]
Corrigido na [v2.6.0](https://github.com/stone-payments/sdk-android/releases/tag/v2.5.6)
