### ISSUE TITLE
SQLiteException ao fazer upgrade de API - impossibilidade de pagamento

### ISSUE THREAD

**Issue by lenoirzamboni** [stone-payments/sdk-android#19]
Olá,

Estávamos usando a API v. 2.2.10, mas como a partir da v.2.4.0 é suportado mensagens de feedback durante o pagamento (TRANSACTION_WAITING_CARD, TRANSACTION_WAITING_PASSWORD, etc), decidimos mudar de API para a v.2.4.2, pois essa é uma feature que o nosso cliente gostaria de possuir.

Porém, após o nosso app fazer auto-update, não é mais possível utilizar o pagamento com cartão. Isso acontece devido a uma SQLiteException, onde o erro relatado é que não existe a coluna `entry_mode`.

Segue o stacktrace da exceção:

``` 
E/SQLiteLog: (1) no such column: entry_mode
W/System.err: android.database.sqlite.SQLiteException: no such column: entry_mode (code 1): , while compiling: UPDATE transaction_base SET type_of_transaction=?,holder_name=?,itk=?,email_client=?,status=?,pinpad_used=?,transaction_reference=?,action_code=?,number_of_instalment=?,aid=?,date=?,arcq=?,amount=?,time=?,atk=?,request_id=?,entry_mode=?,cne=?,icc_related_data=?,sale_key=?,holder_number=?,time_to_pass=?,authorization_code=? WHERE id = '3'
W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1112)
W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:689)
W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
W/System.err:     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
W/System.err:     at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1691)
W/System.err:     at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1639)
W/System.err:     at stone.database.transaction.TransactionDAO.update(TransactionDAO.java:161)
W/System.err:     at stone.providers.TransactionProvider.doInBackground(TransactionProvider.java:181)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
[StoneProvider] Error completing transaction
```
Este problema não acontece quando o cliente desinstala manualmente a versão com a API v.2.2.10 e instala novamente nosso app com API v2.4.2.

Ambiente: Produção
Pinpad usado: Mobipin 10
Android: 4.4.4

**Comment by dprado** [comment]
Olá @filpgame vocês tem uma estimativa pra este fix?

**Comment by filpgame** [comment]
@dprado Boa noite @dprado, quinta feira (28) subiremos uma nova versão com esse fix.

**Comment by dprado** [comment]
obrigado @filpgame

**Comment by filpgame** [comment]
Corrigido na versão [v2.4.6](https://github.com/stone-payments/sdk-android/releases/tag/v2.4.6)!
