### ISSUE TITLE
SSLException em Developer mode impossibilita transação

### ISSUE THREAD

**Issue by lenoirzamboni** [stone-payments/sdk-android#8]
Ao tentar realizar uma transação em **modo developer,** ocorre uma SSLException, sendo impossível realizar a mesma:

```W/SSLCertificateSocketFactory: Bypassing SSL security checks at caller's request
W/System.err: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x6c7dd9a0: I/O error during system call, Connection reset by peer
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
W/System.err:     at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:107)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
W/System.err:     at stone.application.ConnectionPost.execute(ConnectionPost.java:89)
W/System.err:     at stone.providers.TransactionProvider.doInBackground(TransactionProvider.java:216)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
E/logger: ====================================================================
          Nome: null
          SAK: null
          Modelo: null
          Versao do android: null
          Endereco: null, null - null
          ====================================================================
```

Este erro não ocorre em modo produção, apenas ocorre em modo develop. Atualmente, estamos usando o Stone SDK version: 2.2.10, com Android version: 4.4.4

**Comment by matbrandao** [comment]
@LenoirCZ Também tive esse erro. Conversei com os devs da Stone, e aparentemente o ambiente de dev não está operacional. O que me falaram foi pra não utilizar o developer mode.

**Comment by LenoirCZ** [comment]
@matbrandao Obrigado pelo comentário. Espero que esse problema não perdure por muito tempo.

**Comment by jgabrielfreitas** [comment]
@matbrandao  e @LenoirCZ , vamos analisar o ocorrido.
Quais são os devices que vocês estão testando? Ambos estão com problema na versão 4.4.4?

**Comment by filpgame** [comment]
Agora estamos com novas URLs e uma nova forma de alterar o ambiente, mais detalhes no [changelog.md](https://github.com/stone-payments/sdk-android/blob/master/changelog.md#v230)
